insert into Empleados values (NEWID(), 'María Mireya', 'Acevedo Manríquez','Intendencia')
insert into Empleados values (NEWID(), 'Mario Andrés', 'Báez Chávez','Administración' )
insert into Empleados values (NEWID(), 'Prudenciano', 'Caballero Valle','Administración')
insert into Empleados values (NEWID(), 'Guadalupe Voctoriana', 'De León Martínez','Recursos humanos')
insert into Empleados values (NEWID(), 'Carlos Luis', 'Erazo Bernal','Soporte técnico')
insert into Empleados values (NEWID(), 'Jesús Arcadio', 'Fernández Castillo', 'Recursos humanos')
insert into Empleados values (NEWID(), 'Teodoro Quintín', 'Gallegos Alemán', 'Rector')
insert into Empleados values (NEWID(), 'Gustavo Adrián', 'Cerati','Tesorero')
insert into Empleados values (NEWID(), 'Bardo', 'Ibáñez Arago','Intendencia')
insert into Empleados values (NEWID(), 'Thomas Edward', 'Yorke','Administración')