insert into Empleado values (NEWID(), 'María Mireya', 'Acevedo', 'Manríquez', '38', 'FCFM', 'Intendencia')
insert into Empleado values (NEWID(), 'Mario Andrés', 'Báez','Chávez', '34', 'FCQ', 'Administración')
insert into Empleado values (NEWID(), 'Prudenciano', 'Caballero', 'Valle', '29', 'FCB', 'Administración')
insert into Empleado values (NEWID(), 'Guadalupe Voctoriana', 'De León', 'Martínez', '46', 'FIC', 'Recursos humanos')
insert into Empleado values (NEWID(), 'Carlos Luis', 'Erazo', 'Bernal', '98', 'FCF', 'Soporte técnico')
insert into Empleado values (NEWID(), 'Jesús Arcadio', 'Fernández', 'Castillo', '44', 'FM', 'Recursos humanos')
insert into Empleado values (NEWID(), 'Teodoro Quintín', 'Gallegos', 'Alemán', '67', 'FDYC', 'Rector')
insert into Empleado values (NEWID(), 'Gustavo Adrián', 'Cerati','Lolazo', '77', 'FAMUS', 'Tesorero')
insert into Empleado values (NEWID(), 'Bardo', 'Ibáñez', 'Arago', '88', 'FOD', 'Intendencia')
insert into Empleado values (NEWID(), 'Thomas Edward', 'Yorke','Kek', '111', 'FFYL', 'Administración')
