SELECT * FROM Alumno where Facultad='FCFM'
SELECT * FROM Facultad where Campus='Mederos'
SELECT * FROM Carrera where Facultad='FCQ'
SELECT * FROM Empleado where Area='Intendencia'
SELECT * FROM Maestro where Nombre='Bardo'
