insert into Alumnos values (NEWID(), 'María Mireya', 'Acevedo Manríquez', 'FCFM', 'LSTI')
insert into Alumnos values (NEWID(), 'Mario Andrés', 'Báez Chávez', 'FCQ', 'QFB')
insert into Alumnos values (NEWID(), 'Prudenciano', 'Caballero Valle', 'FCB', 'QBP')
insert into Alumnos values (NEWID(), 'Guadalupe Voctoriana', 'De León Martínez', 'FIC', 'CIVIL')
insert into Alumnos values (NEWID(), 'Carlos Luis', 'Erazo Bernal', 'FCF', 'IMRN')
insert into Alumnos values (NEWID(), 'Jesús Arcadio', 'Fernández Castillo', 'FM', 'MCP')
insert into Alumnos values (NEWID(), 'Teodoro Quintín', 'Gallegos Alemán', 'FDYC', 'LC')
insert into Alumnos values (NEWID(), 'Gustavo Adrián', 'Cerati', 'MUSICA', 'TSUM')
insert into Alumnos values (NEWID(), 'Bardo', 'Ibáñez Arago', 'FOD', 'LCE')
insert into Alumnos values (NEWID(), 'Thomas Edward', 'Yorke', 'FFYL', 'LHEH')
