insert into Alumno values (NEWID(), 'María Mireya', 'Acevedo', 'Manríquez', '18', 'FCFM', 'LSTI')
insert into Alumno values (NEWID(), 'Mario Andrés', 'Báez','Chávez', '20', 'FCQ', 'QFB')
insert into Alumno values (NEWID(), 'Prudenciano', 'Caballero', 'Valle', '22', 'FCB', 'QBP')
insert into Alumno values (NEWID(), 'Guadalupe Voctoriana', 'De León', 'Martínez', '19', 'FIC', 'CIVIL')
insert into Alumno values (NEWID(), 'Carlos Luis', 'Erazo', 'Bernal', '21', 'FCF', 'IMRN')
insert into Alumno values (NEWID(), 'Jesús Arcadio', 'Fernández', 'Castillo', '25', 'FM', 'MCP')
insert into Alumno values (NEWID(), 'Teodoro Quintín', 'Gallegos', 'Alemán', '23', 'FDYC', 'LC')
insert into Alumno values (NEWID(), 'Gustavo Adrián', 'Cerati','Lolazo', '18', 'FAMUS', 'TSUM')
insert into Alumno values (NEWID(), 'Bardo', 'Ibáñez', 'Arago', '22', 'FOD', 'LCE')
insert into Alumno values (NEWID(), 'Thomas Edward', 'Yorke','Kek', '19', 'FFYL', 'LHEH')
