insert into Facultad values (NEWID(), 'LSTI', '300', '67', 'CD UNIVERSITARIA')
insert into Facultad values (NEWID(), 'LMAD', '500',  '70', 'CD UNIVERSITARIA')
insert into Facultad values (NEWID(), 'LCC', '600',  '59', 'CD UNIVERSITARIA')
insert into Facultad values (NEWID(), 'LA', '200',  '69', 'CD UNIVERSITARIA')
insert into Facultad values (NEWID(), 'LF', '100',  '79', 'CD UNIVERSITARIA')
insert into Facultad values (NEWID(), 'LM', '150', '68', 'CD UNIVERSITARIA')
insert into Facultad values (NEWID(), 'CIVIL', '5000', '70', 'CD UNIVERSITARIA')
insert into Facultad values (NEWID(), 'IAS', '5000',  '69','CD UNIVERSITARIA')
insert into Facultad values (NEWID(), 'IMA', '2000',  '81', 'CD UNIVERSITARIA')
insert into Facultad values (NEWID(), 'ITS', '1500',  '79', 'CD UNIVERSITARIA')