insert into Maestros values (NEWID(), 'María Mireya', 'Acevedo Manríquez','Matemáticas')
insert into Maestros values (NEWID(), 'Mario Andrés', 'Báez Chávez','Física' )
insert into Maestros values (NEWID(), 'Prudenciano', 'Caballero Valle','Cálculo diferencial')
insert into Maestros values (NEWID(), 'Guadalupe Voctoriana', 'De León Martínez','Cálculo integral')
insert into Maestros values (NEWID(), 'Carlos Luis', 'Erazo Bernal','Base de datos')
insert into Maestros values (NEWID(), 'Jesús Arcadio', 'Fernández Castillo', 'Telecomunicaciones')
insert into Maestros values (NEWID(), 'Teodoro Quintín', 'Gallegos Alemán', 'Competencia comunicativa')
insert into Maestros values (NEWID(), 'Gustavo Adrián', 'Cerati','Apreciacion de las artes')
insert into Maestros values (NEWID(), 'Bardo', 'Ibáñez Arago','Cultura de calidad')
insert into Maestros values (NEWID(), 'Thomas Edward', 'Yorke','Ambiente y sustentabilidad')